name: pawlorie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  firebase_storage: ^11.7.6
  firebase_ui_auth: ^1.14.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  image_picker: ^1.1.1
  intl: ^0.19.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/login.png
    - lib/assets/signup.png
    - lib/assets/no_dog.png

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Bold.ttf
