name: pawlorie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  image_picker: ^1.1.1
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/login.png
    - lib/assets/signup.png

fonts:
  - family: Rubik
    fonts:
      - asset: fonts/Rubik-Bold.ttf
